### ISSUE TITLE
Failed to initialise graphical context

### ISSUE THREAD

**Issue by AleatoricConsonance** [stevebob/roguelike-tutorial-2020#2]
I am having a problem on Part 1 of the tutorial - at the point where the program should display a blank window. The program compiles, but running it yields the following error:

> Finished dev [unoptimized + debuginfo] target(s) in 17.35s
     Running `target/debug/roguelike_tutorial_2021 roguelike_tutorial_2021`
thread 'main' panicked at 'Failed to initialise graphical context: FailedToRequestGraphicsAdapter', src/main.rs:40:6

* My OS is Xubuntu 20.04; installed Rust from standard Rust Install script (not ubuntu repos).
* Downloaded the finished tutorial files, they compile fine, but give same error when attempt to run.
* I suspect that this is some kind of missing library, whether it's not installed, or just can't be found.

Does the tutorial or Chargrid itself have any particular dependencies?

**Comment by stevebob** [comment]
I'll have a go reproducing this today. @AleatoricConsonance heads up that I've made this issue to track the problem https://github.com/stevebob/chargrid-roguelike-tutorial-2020/issues/3. This repo is just an attempt at a website to contain the tutorial, but I instead ended up just making it [part of my blog](https://www.gridbugs.org/roguelike-tutorial-2020/) ([git repo](https://github.com/stevebob/gridbugs.org/tree/master/collections/_roguelike-tutorial-2020)).
